spring:
  application:
    name: blog
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:tc:mysql:8.0.36:///blog?TC_DAEMON=true
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}